#!/usr/bin/env bash

# script for managing brightness
# dependency: brillo <https://gitlab.com/cameronnemo/brillo>

PROG="${0##*/}"
CMD="brillo"

if ! command -v "$CMD" >/dev/null; then
    echo "$PROG: '$CMD' command not found."
    exit 1
fi

function _current {
    local current
    current=$("$CMD" -G)
    echo "${current%.*}"
}

function _statusbar {
    local icon low mid high brightness
    low=""
    mid=""
    high=""
    brightness=$(_current)

    if [[ "$brightness" -lt "30" ]]; then
        icon="$low"
    elif [[ "$brightness" -lt "70" ]]; then
        icon="$mid"
    else
        icon="$high"
    fi

    printf "%s" "${SEP1:-}"
    printf "%s %s\n" "$icon" "$brightness%"
    printf "%s" "${SEP2:-}"
    exit 0
}

function _notify_icon {
    local low mid high
    # shellcheck source=/dev/null
    [[ -f "$HOME/.config/shell/theme.sh" ]] && . "$HOME/.config/shell/theme.sh"
    if [[ "${GLOBAL_THEME:-dark}" == "dark" ]]; then
        high="display-brightness-symbolic"
        low="display-brightness-symbolic"
        mid="display-brightness-symbolic"
    else
        high="display-brightness-symbolic"
        low="display-brightness-symbolic"
        mid="display-brightness-symbolic"
    fi

    local brightness
    brightness=$(_current)

    if [[ "$brightness" -lt "30" ]]; then
        icon="$low"
    elif [[ "$brightness" -lt "70" ]]; then
        icon="$mid"
    else
        icon="$high"
    fi

    echo "${icon}"
}

function _notifyme {
    local brightness args
    declare -a args=(-a "Brightness" "Brightness" "Brightness")
    args+=(-i "$(_notify_icon)")
    args+=(-h string:x-canonical-private-synchronous:brightness)
    args+=(-h int:value:"$(_current)")
    notify-send "${args[@]}"
}

function _increase {
    "$CMD" -A "$1"
}

function _decrease {
    "$CMD" -U "$1"
}

function _usage {
    cat <<-_EOF
Usage: $PROG [INC|DEC] [VALUE]

Simple script for managing brightness

Options:
    -i, inc        Increase brightness by 5%
    -d, dec        Decrease brightness by 5%
    -s, status     Show current brightness
    -h, help       Show this Help
_EOF
    exit
}

function main {
    local option
    option="$1"

    shift

    case "$option" in
    -i | inc) _increase "${1:-3}" ;;
    -d | dec) _decrease "${1:-3}" ;;
    -s | status) _statusbar ;;
    -h | help | --help) _usage ;;
    *) _statusbar ;;
    esac

    _notifyme
}

main "$1" "$2"
