#!/usr/bin/env bash

# ┏┳┓┏━┓┏┓╻╻╺┳╸┏━┓┏━┓
# ┃┃┃┃ ┃┃┗┫┃ ┃ ┃ ┃┣┳┛
# ╹ ╹┗━┛╹ ╹╹ ╹ ┗━┛╹┗╸

LAPTOP="eDP"
EXTERNAL="HDMI-A-0"

restore_wallpaper() {
    nitrogen --restore &>/dev/null
}

case "${1}" in
-l | laptop)
    xrandr --output ${LAPTOP} --mode 1366x768 --output ${EXTERNAL} --off
    ;;
-e | ext | external)
    xrandr --output ${LAPTOP} --off --output ${EXTERNAL} --mode 1920x1080
    ;;
*)
    cat <<-EOF
usage: ${0##*/} [OPTION]

Option:
    -l, laptop      laptop monitor
    -e, external    external monitor
EOF
    exit 1
    ;;
esac

restore_wallpaper
