#!/usr/bin/env bash
#                        _ _
#  _ __ ___   ___  _ __ (_) |_ ___  _ __ ___
# | '_ ` _ \ / _ \| '_ \| | __/ _ \| '__/ __|
# | | | | | | (_) | | | | | || (_) | |  \__ \
# |_| |_| |_|\___/|_| |_|_|\__\___/|_|  |___/
#

LAPTOP="eDP"
EXTERNAL="HDMI-A-0"

restore_wallpaper() {
    nitrogen --restore &>/dev/null
}

main() {
    local monitors
    monitors=$(xrandr --query | grep -w 'connected' | awk '{print $1;}' | wc -l)

    if [ "$monitors" -eq 1 ]; then
        xrandr --output ${LAPTOP} --mode 1366x768 --output ${EXTERNAL} --off
    else
        xrandr --output ${LAPTOP} --off --output ${EXTERNAL} --mode 1920x1080
    fi

    restore_wallpaper
    exit 0
}

main
