#!/bin/sh

# ┏━┓╻ ╻┏━┓
# ┗━┓┃┏┛┗━┓
# ┗━┛┗┛ ┗━┛
# service visual status
# https://smarden.org/runit/
# https://github.com/g-pape/runit/
# https://github.com/g-pape/socklog/

# TODO:
# - [ ] Add 'TIME' for `down` state

# set -eu

PROG=${0##*/}
PAGER="bat -Ppl sh --style=header,grid --paging=never"
SVDIR=${SVDIR:-/var/service}
if [ ! -d "$SVDIR" ]; then
    echo "$PROG: 'SVDIR' directory not found: '$SVDIR'" >&2
    exit 1
fi

# icons
iconok="✓"
iconerr="✗"
iconempty="---"
iconsleep="󰒲"
iconrunning=""

# state
statedown="DOWN"
staterun="RUNNING"
statesleep="SLEEP"

# colors
BLUE=$(tput setaf 4)
CYAN=$(tput setaf 6)
GREEN=$(tput setaf 2)
MAGENTA=$(tput setaf 5)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
DIM=$(tput dim)
BOLD=$(tput bold)
RESET="$(tput sgr0)"

truncate_ellipsis() {
    s=$1
    max=$2

    [ "${#s}" -le "$max" ] && {
        printf "%s" "$s"
        return
    }

    cut=$((max - 3))
    printf "%.*s..." "$cut" "$s"
}

fmt_short() {
    s=$1
    d=$((s / 86400))
    h=$((s % 86400 / 3600))
    m=$((s % 3600 / 60))
    s=$((s % 60))

    if [ "$d" -gt 0 ]; then
        printf "%dd %dh" "$d" "$h"
    elif [ "$h" -gt 0 ]; then
        printf "%dh %dm" "$h" "$m"
    elif [ "$m" -gt 0 ]; then
        printf "%dm %ds" "$m" "$s"
    else
        printf "%ds" "$s"
    fi
}

reset_vars() {
    icon=$iconok
    icon_color=$DIM
    service=""
    status=""
    uptime=""
    uptime_human=""
    state=$staterun
    state_color=$DIM
    enabled=true
    enabled_color=$DIM
    pid=""
    pid_color=$DIM
    command=""
    command_color=$DIM
}

showlogs() {
    menu=fzf
    if ! command -v $menu >/dev/null; then
        echo "$PROG: '$menu' dep not found" >&2
        exit 1
    fi

    : "${SVLOGS:=$HOME/dcs/log/}"
    icon="${YELLOW}${iconrunning}${RESET}"
    service=$(
        for d in "$SVLOGS"/*; do
            if [ -d "$d" ]; then
                name="${d##*/}"
                pidfile="$SVDIR/$name/supervise/pid"
                if [ -s "$pidfile" ]; then
                    display_name="$name $icon"
                else
                    display_name="$name"
                fi

                printf '%s\t%s\n' "$display_name" "$d"
            fi
        done | $menu --prompt="logs> " --with-nth=1 --delimiter='\t' --nth=1 --query="$1" | cut -f2
    )

    [ -n "$service" ] || exit 1
    [ -d "$service" ] || exit 1

    tail -f "$service/current" | $PAGER
}

case "${1:-}" in
-l | --log) shift && showlogs "$1" ;;
*) ;;
esac

# determine state based on priority:
# 1. sleeping (down file + no pid)
# 2. running (has pid)
# 3. down (down file + had pid but stopped)
# 4. fail (no pid, no down file)

# Header
printf " ${BOLD}  %-25s %-10s %-12s %-8s %-16s %-8s${RESET}\n" \
    "SERVICE" "STATE" "ENABLED" "PID" "COMMAND" "TIME"

for path in "$SVDIR"/*; do
    reset_vars
    service=${path##*/}

    status=$(sv status "$service" 2>/dev/null)

    if [ -f "$path/supervise/pid" ]; then
        pid=$(cat "$path/supervise/pid")
    fi

    if [ -n "$pid" ]; then
        # RUNNING
        # uptime=${status##*) }
        uptime=$(echo "$status" | sed -n 's/^run: [^:]*: (pid [0-9]*) \([0-9]*s\).*/\1/p')
        uptime=${uptime%s}
        uptime_human=$(fmt_short "$uptime" 2>/dev/null)
        uptime_human_color="$DIM"
        [ -z "$uptime_human" ] && {
            uptime_human="error"
            uptime_human_color="$RED"
        }

        # ps xf -o pid,ppid,pgrp,euser,args
        command=$(ps -p "$pid" -o comm=)
        command=$(truncate_ellipsis "$command" 16)
        command_color=$CYAN

        pid_color=$MAGENTA

        state_color=$GREEN
        enabled=true
        enabled_color=$BLUE
        icon="$iconok"
        icon_color=$GREEN

    elif [ -f "$path/down" ]; then
        # SLEEP
        state="$statesleep"
        state_color=$DIM
        enabled=false
        enabled_color=$RED

        pid="$iconempty"
        command="$iconempty"
        uptime_human="$iconempty"

        icon="$iconsleep"
        icon_color=$DIM

    else
        # FAIL
        state="$statedown"
        state_color=$RED

        enabled=false
        enabled_color=$RED

        pid="$iconempty"
        command="$iconempty"
        uptime_human="$iconempty"

        icon="$iconerr"
        icon_color=$RED
    fi

    # patch n1
    if [ -n "$pid" ] && [ -f "$path/down" ]; then
        enabled=false
        enabled_color=$RED
    fi

    printf " %s%s%s %-25s %s%-10s%s %s%-12s%s %s%-8s%s %s%-16s%s %s%-8s%s\n" \
        "$icon_color" "$icon" "$RESET" "$service" \
        "$state_color" "$state" "$RESET" \
        "$enabled_color" "$enabled" "$RESET" \
        "$pid_color" "$pid" "$RESET" \
        "$command_color" "$command" "$RESET" \
        "$uptime_human_color" "$uptime_human" "$RESET"
done
