#!/usr/bin/env bash

# Script for displaying bluetooth devices status in dwm bar.
#
# Output: [ DEVICE 98%,  DEVICE 42%]

PROG=$(basename "$0")
LOGGER="${LOGS_PATH:-$HOME/dcs/log}/${PROG}.log"

# devices icon
ICON_HEADPHONES="BT"
ICON_DEV_DEFAULT="BT"
if ((DWM_BAR_UNICODE)); then
    if ((DWM_BAR_FILLED)); then
        ICON_HEADPHONES=""  #   󰋋 
        ICON_DEV_DEFAULT="󰎇" # ""
    else
        ICON_HEADPHONES="" #   󰋋 
        ICON_DEV_DEFAULT=""
    fi
fi

# battery icons
warn="🔴"
if ((DWM_BAR_UNICODE)); then
    icon_critical="󰤿 "
    icon_empty="󰤿 "
    icon_low="󰥀 "
    icon_mid="󰥂 "
    icon_full="󰥈 "
    icon_unknown="󰥇 "
fi

declare -A DEVICES=(
    ["audio-headset"]="$ICON_HEADPHONES"
    ["audio-headphones"]="$ICON_HEADPHONES"
    ["audio-card"]="$ICON_DEV_DEFAULT"
)

function is_power_on {
    if bluetoothctl show | grep -q "Powered: yes"; then
        return 0
    else
        return 1
    fi
}

if ! is_power_on; then
    exit
fi

function _notifyme {
    local msg="$1"
    local urgency="$2"
    local cmd="notify-send"
    export DISPLAY=":0"

    if command -v dunstify >/dev/null; then
        cmd="dunstify"
    fi

    "$cmd" -h string:x-dunst-stack-tag:bluetooth -i "battery-low-symbolic" -u "$urgency" "$PROG" "$msg"
}

function _check_battery {
    local device_alias="$1"
    local battery="$2"
    if [[ "$battery" -le 10 ]] && [[ "$battery" != "" ]]; then
        msg="$device_alias battery is low ${warn} ${icon_critical}${battery}%"
        echo "$(date +"%Y-%m-%d %H:%M:%S") - $msg" | tee -a "$LOGGER" >/dev/null
        _notifyme "$msg" "critical"
    fi
}

function is_device_connected {
    local device device_info
    device="$1"
    device_info=$(bluetoothctl info "$device")
    if echo "$device_info" | grep -q "Connected: yes"; then
        return 0
    else
        return 1
    fi
}

function get_device_battery {
    local device battery
    device="$1"
    battery=$(bluetoothctl info "$device" | grep "Battery Percentage:" | awk '{print $4}' | tr -d '()')
    echo "$battery"
}

function get_device_alias {
    local device device_alias
    device="$1"
    device_alias=$(bluetoothctl info "$device" | grep "Alias" | cut -d ' ' -f 2-)
    echo "$device_alias"
}

function get_battery_icon {
    local bat_charge icon
    icon=""
    bat_charge="$1"

    if [[ -z "$bat_charge" ]]; then
        echo "$icon_unknown"
        return
    fi

    if [[ "$bat_charge" -lt "20" ]]; then
        icon="$warn$icon_critical"
    elif [[ "$bat_charge" -lt "30" ]]; then
        icon="$icon_empty"
    elif [[ "$bat_charge" -lt "50" ]]; then
        icon="$icon_low"
    elif [[ "$bat_charge" -lt "90" ]]; then
        icon="$icon_mid"
    else
        icon="$icon_full"
    fi

    echo "$icon"
}

function get_device_icon {
    local device_icon_name
    device="$1"

    device_icon_name=$(bluetoothctl info "$device" | grep "Icon" | cut -d ' ' -f 2-)

    if [[ -n "${DEVICES[$device_icon_name]}" ]]; then
        echo "${DEVICES[$device_icon_name]}"
    else
        echo "${ICON_DEV_DEFAULT}"
    fi
}

function devices_status {
    local device_counter=0
    mapfile -t paired_devices < <(bluetoothctl devices | grep Device | cut -d ' ' -f 2)

    for device in "${paired_devices[@]}"; do
        is_device_connected "$device" || continue

        battery=$(get_device_battery "$device")
        [[ -z "$battery" ]] && continue

        device_alias=$(get_device_alias "$device")
        _check_battery "$device_alias" "$battery"
        ((DWM_BAR_COLOR)) && {
            if [[ "$battery" -le 10 ]] && [[ "$battery" != "" ]]; then
                device_alias="${DWM_BAR_WARNING:-}${device_alias}${DWM_BAR_END:-}"
            else
                device_alias="${DWM_BAR_FG:-}${device_alias}${DWM_BAR_END:-}"
            fi
        }

        bat_icon=$(get_battery_icon "$battery")

        if ((DWM_BAR_UNICODE)); then
            device_icon=$(get_device_icon "$device")
            string="${device_icon} ${device_alias} ${bat_icon}${battery}%"
        else
            string="${device_alias} ${battery}%"
        fi

        ((device_counter++))
        devices_output+="${devices_output:+, }$string"
    done

    echo "$devices_output"
}

(($(bluetoothctl info | grep -c 'Name') == 0)) && exit
((DWM_BAR_UNICODE)) && {
    printf "%s%s%s\n" \
        "${SEP1:-}" \
        "$(devices_status)" \
        "${SEP2:-}"
    exit
}

printf "%s\n" "$(devices_status)"
