#!/usr/bin/env bash

# Script for displaying CPU usage
#
# Output: [ICON 10%]
#   

ICON="CPU"
((DWM_BAR_UNICODE)) && { ((DWM_BAR_FILLED)) && ICON=" " || ICON=" "; }
((DWM_BAR_COLOR && !DWM_BAR_UNICODE)) && ICON="${DWM_BAR_FG:-}${ICON}${DWM_BAR_END:-}"

CPU=$(top -bn1 | grep Cpu | awk '{print $2}')
digits=${#CPU}
space=" "
((digits == 1)) && space="  "

printf "%s%s%s%s%%%s\n" \
    "${SEP1:-}" \
    "${ICON}" \
    "${space}" \
    "$CPU" \
    "${SEP2:-}"
