#!/usr/bin/env python3

import os
import sys

import psutil

#  
#                   
#    c          

# TODO:
# [ ] Better main function
# [ ] Performance

SEP1 = os.environ.get('SEP1', '')
SEP2 = os.environ.get('SEP2', '')

programs = {
    'redshift': '',
    'bitwarden': '',
    'dropbox': '',
    # 'firefox': '',
    'galculator': '',
    'git': '',
    'librewolf': '',
    'mpv': '',
    'newsboat': '',
    'pcmanfm': '',
    'signal-desktop': '',
    'telegram-desktop': '',
    'tg': '',
    'tidal-hifi': '',
    'transmission-daemon': '',
    'tuir': '',
    'vlc': '',
    'chromium': '',
    # 'vim': '',
    # 'nvim': '',
    'ollama': '',
}


services = {
    'vpn': '',
    'no-vpn': '',
    'wlp2s0': '',
    'eno1': '',
    'no-internet': '',
}


def find_process(process_name) -> bool:
    for process in psutil.process_iter(['pid', 'name']):
        if process.info['name'] == process_name:
            return True
    return False


def main() -> int:
    print(SEP1, end='')
    for idx, (program, icon) in enumerate(programs.items()):
        if find_process(program):
            if idx == len(programs) - 1:
                print(icon, end='')
            else:
                print(icon, end=' ')
    print(SEP2)

    return 0


if __name__ == '__main__':
    sys.exit(main())
