#!/usr/bin/env bash

# Script for displaying core temperature in dwm bar.
#
# Output: [icon 55°C]

# icons:     
PROG=$(basename "$0")
TARGET="k10temp-pci-00c3"
WARN_ICON="🔥"
WARN_TEMP=75
MAX_TEMP=92
NOTIFYID=888
WARN_NOTIFIED="/tmp/${PROG}-high"

if ((DWM_BAR_UNICODE)); then
    icon_cold=""
    icon_low=""
    icon_mid=""
    icon_high=""
    icon_extreme=""
fi

function _notify {
    local msg="$1"
    export DISPLAY=":0"
    declare -a notify_args=(-h string:x-dunst-stack-tag:temppercore)
    notify_args+=(-i "cpu" -u critical)
    notify_args+=(-r "$NOTIFYID")
    notify-send "${notify_args[@]}" "$PROG" "$msg"
}

_get_icon() {
    local temp=$1
    case $temp in
    2[0-9] | 3[0-9]) echo "$icon_cold" ;; # 20–39
    4[0-9]) echo "$icon_low" ;;           # 40–49
    5[0-9]) echo "$icon_mid" ;;           # 50–59
    6[0-9]) echo "$icon_high" ;;          # 60–69
    7[0-8]) echo "$icon_extreme" ;;       # 70–78
    *) echo "$WARN_ICON" ;;               # >=79 or <20
    esac
}

function _cpu_tempcore {
    local temp_str temp_int ICON
    temp_str=$(sensors "$TARGET" | awk '/Tctl/ {gsub(/\+/, "", $2); print $2}')
    temp_int=${temp_str%.*} # strip decimal

    # local monitors
    # monitors=$(xrandr --query | grep -w 'connected' | awk '{print $1;}' | wc -l)
    # [[ "$temp_int" -le "$MIN_TEMP" && "$monitors" -eq 1 ]] && exit

    ICON="TEMP"
    ((DWM_BAR_UNICODE)) && ICON=$(_get_icon "$temp_int")

    # --- high temperature warning ---
    if ((temp_int >= MAX_TEMP)); then
        _notify "${temp_str} is too high"
        : >"$WARN_NOTIFIED" # create the file safely
    fi

    printf "%s" "${SEP1:-}"

    # --- display formatting ---
    if ((temp_int >= "${WARN_TEMP}")); then
        # WARNING COLOR
        printf "%s%s%s %s\n" \
            "${DWM_BAR_WARNING:-}" \
            "$ICON" \
            "${DWM_BAR_END:-}" \
            "$temp_str"
    else
        ((DWM_BAR_COLOR)) && ICON="${DWM_BAR_FG:-}${ICON}${DWM_BAR_END:-}"
        printf "%s %s\n" "$ICON" "$temp_str"
    fi

    printf "%s" "${SEP2:-}"

    # --- close warning if temp is back to normal ---
    if ((temp_int < MAX_TEMP)) && [[ -e "$WARN_NOTIFIED" ]]; then
        dunstctl close "$NOTIFYID"
        rm "$WARN_NOTIFIED"
    fi
}

_cpu_tempcore
