#!/usr/bin/env bash

# Script for displaying battery status in dwm bar.
#
# Output: [UNICODE 98%]
# Output: [UNICODE 98% status]

BAT_CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
BAT_STATUS=$(cat /sys/class/power_supply/BAT0/status)
CRITICAL=10
NOTIFIED="/tmp/battery_notified"
[[ "$BAT_STATUS" == "Full" ]] && exit 0

# notification icons
if ((DWM_BAR_UNICODE)); then
    if ((DWM_BAR_FILLED)); then
        ICON_SET=(" " " " " " " " " " "")
    else
        ICON_SET=("󰂎" "󰁺" "󰁼" "󰁿" "󰁹" "")
    fi

    icon_critical="${ICON_SET[0]}"
    icon_empty="${ICON_SET[1]}"
    icon_low="${ICON_SET[2]}"
    icon_mid="${ICON_SET[3]}"
    icon_full="${ICON_SET[4]}"
    icon_char="${ICON_SET[5]}"
fi

function _notifyme {
    local mesg="${1:-Battery}"
    local icon="${2:-}"
    local urgency="${3:-normal}"
    local args=(-a "Battery" "Battery" "${mesg}")
    args+=(-r 999 --urgency="${urgency}")
    args+=(-i "${icon}")
    args+=(-h int:value:"$BAT_CHARGE")
    args+=(-h string:x-canonical-private-synchronous:battery)
    notify-send "${args[@]}"

    touch "$NOTIFIED"
}

function _is_charching {
    if [[ "$BAT_STATUS" != "Charging" ]]; then
        return 1
    fi
    return 0
}

function _get_charging_bar_short {
    local start=""
    local full=""
    local empty=""
    local end_empty=""
    # local end_full="" # <-
    local charge_level icon
    charge_level=$((BAT_CHARGE / 10))
    icon="${start}$(printf '%s%.0s' "${full}" $(seq 1 "$charge_level"))$(printf '%s%.0s' "${empty}" $(seq "$charge_level" 8))${end_empty}"
    echo "$icon"
}

function _get_charging_bar_other {
    local bars=("" "▏" "▎" "▍" "▌" "▋" "▊" "▉" "█")
    local index=$((BAT_CHARGE * 8 / 100))
    echo "[${bars[index]}${BAT_CHARGE}%]"
}

function _get_charging_bar {
    # Output: [  50%]
    #  
    # ▓ ▒ ░
    local icon_start=""
    local icon_full=""
    local icon_empty=""
    local icon_end_empty=""
    local icon_end_full=""
    local icon="$icon_start"

    local charge_level
    charge_level=$((BAT_CHARGE / 10))

    for i in $(seq 2 9); do
        if [[ $i -le $charge_level ]]; then
            icon+="$icon_full"
        else
            icon+="$icon_empty"
        fi
    done

    if [[ $charge_level -ge 10 ]]; then
        icon+="$icon_end_full"
    else
        icon+="$icon_end_empty"
    fi

    echo "$icon"
}

function _get_icon {
    local icon=""
    local icon_set=("${icon_critical}" "${icon_empty}" "${icon_low}" "${icon_mid}" "${icon_full}")
    local idx

    if ((BAT_CHARGE < 20)); then
        idx=0
    elif ((BAT_CHARGE < 30)); then
        idx=1
    elif ((BAT_CHARGE < 50)); then
        idx=2
    elif ((BAT_CHARGE < 90)); then
        idx=3
    else
        idx=4
    fi

    echo "${icon_set[idx]}"
}

function _display_charging_bar {
    local ICON="CHAR"

    ((DWM_BAR_UNICODE)) && ICON="$(_get_charging_bar)"

    if ((DWM_BAR_COLOR)); then
        if ((BAT_CHARGE <= 20)); then
            DWM_BAR_FG="${DWM_BAR_WARNING}"
        elif ((BAT_CHARGE >= 80)); then
            DWM_BAR_FG="${DWM_BAR_HEALTHY}"
        fi
        ICON="${DWM_BAR_FG:-}${ICON}${DWM_BAR_END:-}"
    fi

    if ((DWM_BAR_UNICODE)); then
        printf "%b %b %s%%" "${ICON}" "$icon_char" "$BAT_CHARGE"
        return
    fi

    printf "%b%b %s%%" "${ICON}" "$icon_char" "$BAT_CHARGE"
}

function _display_icon {
    local ICON="BAT"
    ((DWM_BAR_UNICODE)) && ICON=$(_get_icon)
    if ((DWM_BAR_COLOR)); then
        ((BAT_CHARGE < 20)) && DWM_BAR_FG="${DWM_BAR_WARNING}"
        ICON="${DWM_BAR_FG:-}${ICON}${DWM_BAR_END:-}"
    fi

    printf "%s %d%%" "${ICON}" "${BAT_CHARGE}"
}

function _render_unicodes {
    printf "%s" "${SEP1:-}"
    if _is_charching; then
        _display_charging_bar
    else
        _display_icon
    fi
    printf "%s\n" "${SEP2:-}"
}

function main {
    # if not charging and low charge level critical notification
    if ! _is_charching &&
        [[ "$BAT_CHARGE" -le "$CRITICAL" ]] &&
        [[ ! -f "$NOTIFIED" ]]; then
        _notifyme "Battery critical: " "battery-level-10-symbolic" "critical"
    fi

    # remove the file if it was notified, and the battery is not low or if the
    # battery is not charging
    if [[ -f "$NOTIFIED" ]] &&
        ! _is_charching &&
        [[ "$BAT_CHARGE" -gt "$CRITICAL" ]]; then
        _notifyme "Battery: " "battery-level-70-symbolic" "normal"
        rm -f "$NOTIFIED"
    fi

    _render_unicodes
}

main
