#!/usr/bin/env bash

# ╺┳┓┏━┓╺┳╸┏━╸
#  ┃┃┣━┫ ┃ ┣╸
# ╺┻┛╹ ╹ ╹ ┗━╸
# formatted date.
#
# output: "[ICON Fri, DD MMM]"
#       󰭦 󰭨 

(($(xrandr | grep -c '\bconnected\b') == 2)) && exit

DATE=$(date "+%a %d %b")
ICON="DATE"
((DWM_BAR_UNICODE)) && { ((DWM_BAR_FILLED)) && ICON=" " || ICON=" "; }
((DWM_BAR_COLOR)) && ICON="${DWM_BAR_FG:-}${ICON}${DWM_BAR_END:-}"

printf "%s%s %s%s\n" \
    "${SEP1:-}" \
    "${ICON}" \
    "${DATE}" \
    "${SEP2:-}"
