#!/usr/bin/env bash

# script for displaying mpd/tidal-hifi status
#
# output:
#  artist - track 00:00/00:00

set -euo pipefail

# (($(xrandr | grep -c '\bconnected\b') == 1)) && exit

PLAYING=""
((DWM_UNICODE)) && { ((DWM_BAR_FILLED)) && PLAYING="" || PLAYING=""; }

function _logerr {
    printf "%s: %s\n" "${0##*/}" "$*" >&2
    exit 1
}

function _is_running {
    local cmd="$1"

    case "$cmd" in
    # "mpd") pgrep -f "$cmd" >/dev/null ;;
    "tidal-hifi") curl -s http://localhost:47836/current >/dev/null ;;
    # "mpv") pgrep -f "$cmd" >/dev/null ;;
    *) pgrep -f "$cmd" >/dev/null ;;
    esac
}

function _mpd_status {
    local status artist track
    status=$(mpc status | sed -n 2p | awk '{print $1;}')
    if [[ "$status" = "[paused]" || "$status" = "" ]]; then
        return
    else
        status=$PLAYING
    fi

    artist=$(mpc current -f %artist%)
    track=$(mpc current -f %title%)

    # pos=$(mpc status | grep "%)" | awk '{ print $3 }' | awk -F/ '{ print $1 }')
    # dur=$(mpc current -f %time%)
    # printf "%s %s - %s %s/%s\n" "$status" "$artist" "$track" "$pos" "$dur"
    #
    printf "%s %s - %s\n" "$status" "$artist" "$track"
}

function _mpv_status {
    local deps=(jq socat mpv)
    for cmd in "${deps[@]}"; do
        if ! command -v "${cmd}" >/dev/null; then
            _logerr "'${cmd}' not found"
        fi
    done

    [[ ! -e "${MPVSOCKET:-}" ]] && return

    local title
    title=$(echo '{ "command": ["get_property", "media-title"] }' | socat - "$MPVSOCKET" 2>/dev/null | jq -r .data)
    local retcode="$?"
    [[ "${retcode}" -ne 0 ]] && return
    local icon=""
    if [[ "${title}" == "index.m3u8" ]]; then
        title="YouTube Live"
    fi
    echo "${icon}  ${title}"
}

function _tidal_status {
    if ! command -v jq >/dev/null; then
        _logerr "jq not found"
    fi

    local json track artist status
    local host="http://localhost:47836"
    json=$(curl -s "$host/current")
    [[ -z "$json" ]] && _logerr "err fetching tidal-hifi status"

    status=$(echo "$json" | jq -r '.status')
    if [[ "$status" = "paused" ]]; then
        return
    else
        status=$PLAYING
    fi

    track=$(echo "$json" | jq -r '.title')
    artist=$(echo "$json" | jq -r '.artist')
    artist="${artist^^}"
    ((DWM_COLOR)) && artist="${DWM_BAR_FG:-}${artist}${DWM_BAR_END:-}"

    # pos=$(echo "$json" | jq -r '.current')
    # dur=$(echo "$json" | jq -r '.duration')
    # printf "%s %s - %s %s/%s\n" "$status" "$artist" "$track" "$pos" "$dur"

    printf "%s %s - %s\n" "$status" "$artist" "$track"
}

function main {
    if _is_running "tidal-hifi"; then
        _tidal_status
    elif _is_running "mpd"; then
        _mpd_status
    elif _is_running "mpv"; then
        _mpv_status
    fi
}

main
