#!/usr/bin/env bash

# Script for displaying volume status in dwm bar.
#
# Output: [ICON 55%]

PROG=$(basename "$0")
ICON_BAR="VOL"
ICON_NOTIFY=""

case "${BLOCK_BUTTON:-}" in
1) setsid --fork pavucontrol ;;
2) notify-send "TWO" "...." ;;
4) wpctl set-volume 3%+ ;;
5) wpctl set-volume 3%- ;;
6) terminal -e "${EDITOR:-nvim}" "$0" ;;
*) ;;
esac

# bar icons
if ((DWM_UNICODE)); then
    if ((DWM_BAR_FILLED)); then
        ICON_SET=("" "" "" "")
    else
        ICON_SET=("" "" "" "")
    fi

    low_icon="${ICON_SET[0]}"
    mid_icon="${ICON_SET[1]}"
    high_icon="${ICON_SET[2]}"
    muted_icon="${ICON_SET[3]}"
fi

# notification icons
noti_low_icon="audio-volume-low-symbolic"
noti_med_icon="audio-volume-medium-symbolic"
noti_high_icon="audio-volume-high-symbolic"
noti_over_icon="audio-volume-overamplified-symbolic"
noti_muted_icon="audio-volume-muted-symbolic"

# shellcheck source=/dev/null
[[ -f "$HOME/.config/shell/theme.sh" ]] && . "$HOME/.config/shell/theme.sh"

if [[ "${GLOBAL_THEME:-dark}" == "light" ]]; then
    path="/usr/share/icons/Papirus-Light/24x24/panel"
    noti_low_icon="${path}/audio-volume-low.svg"
    noti_med_icon="${path}/audio-volume-medium.svg"
    noti_high_icon="${path}/audio-volume-high.svg"
    noti_over_icon="$noti_high_icon"
    noti_muted_icon="${path}/audio-volume-muted.svg"
fi

if ! command -v wpctl >/dev/null; then
    err="'wpctl' not found"
    printf "%s: %s\n" "$PROG" "$err"
    notify-send "$PROG" "$err"
    exit 1
fi

VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}')
VOL=$(awk "BEGIN { printf \"%.0f\n\", $VOL * 100 }")

function is_muted {
    local status
    status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)

    if [[ "${status}" =~ "MUTED" ]]; then
        return 0
    fi

    return 1
}

function load_icons {
    if is_muted || [[ "$VOL" -eq 0 ]]; then
        ICON_BAR="$muted_icon"
        ICON_NOTIFY="$noti_muted_icon"
    elif [[ "$VOL" -gt 0 && "$VOL" -le 15 ]]; then
        ICON_BAR="$low_icon"
        ICON_NOTIFY="$noti_low_icon"
    elif [[ "$VOL" -gt 15 && "$VOL" -le 65 ]]; then
        ICON_BAR="$mid_icon"
        ICON_NOTIFY="$noti_med_icon"
    elif [[ "$VOL" -gt 65 && "$VOL" -le 100 ]]; then
        ICON_BAR="$high_icon"
        ICON_NOTIFY="$noti_high_icon"
    else
        ICON_BAR="$high_icon"
        ICON_NOTIFY="$noti_over_icon"
    fi
}

function _notify {
    local icon="$1"
    local cmd=notify-send
    local appname="Volume"

    declare -a notify_args=(-a "$appname" "$appname: ")
    notify_args+=(-i "$icon")
    notify_args+=(-h int:value:"$VOL")
    notify_args+=(-h "string:x-canonical-private-synchronous:volume")
    "$cmd" "${notify_args[@]}"
}

function main {
    ((DWM_UNICODE)) && load_icons
    [[ -z "$VOL" ]] && VOL="?"
    ((DWM_COLOR)) && ICON_BAR="${DWM_BAR_FG:-}${ICON_BAR}${DWM_BAR_END:-}"
    printf "%s%s  %s%%%s\n" "${SEP1:-}" "$ICON_BAR" "$VOL" "${SEP2:-}"
    _notify "$ICON_NOTIFY"
}

main
