#!/usr/bin/env bash

# Script for displaying pomodoro status in dwm bar.
#
# Output: [ICON time]

CMD=timer

if ! command -v "$CMD" >/dev/null; then
    printf "%s\n" "err: $CMD not found"
    exit 1
fi

status=$($CMD status)
[[ -z "$status" ]] && exit

ICON="POM"
((DWM_BAR_UNICODE)) && { ((DWM_BAR_FILLED)) && ICON="" || ICON=""; }
((DWM_BAR_COLOR)) && ICON="${DWM_BAR_FG:-}${ICON}${DWM_BAR_END:-}"

printf "%s%s %s%s\n" \
    "${SEP1:-}" \
    "${ICON}" \
    "${status}" \
    "${SEP2:-}"
