#!/usr/bin/env bash

# Script for displaying current time in dwm bar.
#
# Output: [ICON 16:12]

ICON="TIME"
((DWM_UNICODE)) && { ((DWM_BAR_FILLED)) && ICON=" " || ICON=" "; }
((DWM_COLOR)) && ICON="${DWM_BAR_FG:-}${ICON}${DWM_BAR_END:-}"
printf "%s%s %s%s\n" "${SEP1:-}" "$ICON" "$(date "+%H:%M")" "${SEP2:-}"
