#!/usr/bin/env bash

# script for displaying mpd/tidal-hifi status
#
# output:
#  artist - track 00:00/00:00

set -euo pipefail

# (($(xrandr | grep -c '\bconnected\b') == 1)) && exit

ICON="MPV"
PLAYING=""
((DWM_BAR_UNICODE)) && { ((DWM_BAR_FILLED)) && PLAYING="" || PLAYING=""; }

function _logerr {
    printf "%s: %s\n" "${0##*/}" "$*" >&2
    exit 1
}

function _truncate {
    local str=$1
    local max="${2:-18}"
    local length="${#str}"

    ((length <= max)) && {
        echo "${str}"
        return
    }

    local trunc
    trunc=$(printf "%s" "$str" | cut -c 1-"$max")
    trunc+="…"

    echo "${trunc}"
}

function _is_running {
    local cmd="$1"

    case "$cmd" in
    # "mpd") pgrep -f "$cmd" >/dev/null ;;
    "tidal-hifi") curl -s http://localhost:47836/current >/dev/null ;;
    # "mpv") pgrep -f "$cmd" >/dev/null ;;
    *) pgrep -f "$cmd" >/dev/null ;;
    esac
}

function _mpd_status {
    local status artist track
    status=$(mpc status | sed -n 2p | awk '{print $1;}')
    if [[ "$status" = "[paused]" || "$status" = "" ]]; then
        return
    else
        status=$PLAYING
    fi

    track=$(mpc current -f %title%)
    artist=$(mpc current -f %artist%)
    artist="${artist^^}"
    artist=$(_truncate "${artist}")
    ((DWM_BAR_COLOR)) && artist="${DWM_BAR_FG:-}${artist}${DWM_BAR_END:-}"

    printf "%s %s - %s\n" "$status" "$artist" "$track"
}

function _mpv_status {
    local deps=(jq socat mpv)
    for cmd in "${deps[@]}"; do
        if ! command -v "${cmd}" >/dev/null; then
            _logerr "'${cmd}' not found"
        fi
    done

    [[ ! -e "${MPVSOCKET:-}" ]] && return

    local title
    title=$(echo '{ "command": ["get_property", "media-title"] }' | socat - "$MPVSOCKET" 2>/dev/null | jq -r .data)
    local retcode="$?"

    [[ "${retcode}" -ne 0 ]] && return

    case "${title}" in
    index.m3u8) title="YouTube Live" ;;
    *watch?v=*) title="Loading..." ;;
    esac
    title=$(_truncate "${title}" 30)
    ((DWM_BAR_COLOR)) && ICON="${DWM_BAR_FG:-}${ICON}${DWM_BAR_END:-}"
    echo "${ICON} ${title}"
}

function _tidal_status {
    if ! command -v jq >/dev/null; then
        _logerr "jq not found"
    fi

    local json track artist status
    local host="http://localhost:47836"
    json=$(curl -s "$host/current")
    [[ -z "$json" ]] && _logerr "err fetching tidal-hifi status"

    status=$(echo "$json" | jq -r '.status')
    if [[ "$status" = "paused" ]]; then
        return
    else
        status=$PLAYING
    fi

    track=$(echo "$json" | jq -r '.title')
    artist=$(echo "$json" | jq -r '.artist')
    artist="${artist^^}"
    artist=$(_truncate "${artist}")
    ((DWM_BAR_COLOR)) && artist="${DWM_BAR_FG:-}${artist}${DWM_BAR_END:-}"

    printf "%s %s - %s\n" "$status" "$artist" "$track"
}

function main {
    if _is_running "tidal-hifi"; then
        _tidal_status
    elif _is_running "mpv"; then
        _mpv_status
    elif _is_running "mpd"; then
        _mpd_status
    fi
}

main
