#!/usr/bin/env bash

# ╺┳┓┏━┓╺┳╸┏━╸
#  ┃┃┣━┫ ┃ ┣╸
# ╺┻┛╹ ╹ ╹ ┗━╸
# formatted date.
#
# output: "[ICON Fri, DD MMM]"
#        󰭦 󰭨 

(($(xrandr | grep -c '\bconnected\b') == 1)) && exit
ICON="DATE"
((DWM_UNICODE)) && { ((DWM_BAR_FILLED)) && ICON=" " || ICON=" "; }
((DWM_COLOR)) && ICON="${DWM_BAR_FG:-}${ICON}${DWM_BAR_END:-}"

printf "%s%s %s%s\n" \
    "${SEP:-}" \
    "$ICON" \
    "$(date "+%a %d %b")" \
    "${SEP:-}"
