#!/usr/bin/env bash

# Script for displaying volume status in dwm bar.
#
# Output: [ICON 55%]

PROG=$(basename "$0")
ICON_BAR=""
ICON_NOTIFY=""

# bar icons
if ((DWM_BAR_UNICODE)); then
    if ((DWM_BAR_FILLED)); then
        ICON_SET=("" "" "" "")
    else
        ICON_SET=("" "" "" "")
    fi

    low_icon="${ICON_SET[0]}"
    mid_icon="${ICON_SET[1]}"
    high_icon="${ICON_SET[2]}"
    muted_icon="${ICON_SET[3]}"
fi

# notification icons
noti_low_icon="audio-volume-low-symbolic"
noti_med_icon="audio-volume-medium-symbolic"
noti_high_icon="audio-volume-high-symbolic"
noti_over_icon="audio-volume-overamplified-symbolic"
noti_muted_icon="audio-volume-muted-symbolic"

# shellcheck source=/dev/null
[[ -f "$HOME/.config/shell/theme.sh" ]] && . "$HOME/.config/shell/theme.sh"

if [[ "${GLOBAL_THEME:-dark}" == "light" ]]; then
    path="/usr/share/icons/Papirus-Light/24x24/panel"
    noti_low_icon="${path}/audio-volume-low.svg"
    noti_med_icon="${path}/audio-volume-medium.svg"
    noti_high_icon="${path}/audio-volume-high.svg"
    noti_over_icon="$noti_high_icon"
    noti_muted_icon="${path}/audio-volume-muted.svg"
fi

if ! command -v wpctl >/dev/null; then
    err="'wpctl' not found"
    printf "%s: %s\n" "$PROG" "$err"
    notify-send "$PROG" "$err"
    exit 1
fi

VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}')
VOL=$(awk "BEGIN { printf \"%.0f\n\", $VOL * 100 }")

function _is_muted {
    local status
    status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)

    if [[ "${status}" =~ "MUTED" ]]; then
        return 0
    fi

    return 1
}

function _load_icons {
    local ICON_BAR_SET=("$muted_icon" "$low_icon" "$mid_icon" "$high_icon" "$high_icon")
    local ICON_NOTIFY_SET=("$noti_muted_icon" "$noti_low_icon" "$noti_med_icon" "$noti_high_icon" "$noti_over_icon")

    local idx
    if _is_muted || ((VOL == 0)); then
        idx=0
    elif ((VOL <= 15)); then
        idx=1
    elif ((VOL <= 65)); then
        idx=2
    elif ((VOL <= 100)); then
        idx=3
    else
        idx=4
    fi

    ICON_BAR="${ICON_BAR_SET[idx]}"
    ICON_NOTIFY="${ICON_NOTIFY_SET[idx]}"
}

function _notify {
    local icon="$1"
    local cmd=notify-send
    local appname="Volume"

    declare -a notify_args=(-a "$appname" "$appname: ")
    notify_args+=(-i "$icon")
    notify_args+=(-h int:value:"$VOL")
    notify_args+=(-h "string:x-canonical-private-synchronous:volume")
    "$cmd" "${notify_args[@]}"
}

function main {
    _load_icons
    [[ -z "$VOL" ]] && VOL="?"

    ((!DWM_BAR_UNICODE)) && ICON_BAR=$(_is_muted && printf "MUT" || printf "VOL")
    ((DWM_BAR_COLOR)) && ICON_BAR="${DWM_BAR_FG:-}${ICON_BAR}${DWM_BAR_END:-}"

    digits=${#VOL}
    space=" "
    ((digits == 3)) && space=" "

    printf "%s%s%s%s%%%s\n" \
        "${SEP1:-}" \
        "$ICON_BAR" \
        "${space}" \
        "$VOL" \
        "${SEP2:-}"

    _notify "$ICON_NOTIFY"
}

main
